// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client'

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship['fields'][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship['id']]: ContentRelationshipFieldWithData<
      TSubRelationship['customtypes'],
      TLang
    >
  } & // Group
  {
    [TGroup in Extract<
      TRelationship['fields'][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup['id']]: TData[TGroup['id']] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship['fields'][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never
  }

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >['id']]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>['data'],
      TLang
    >
  >
}[Exclude<TCustomType[number], string>['id']]

/**
 * Item in *Artist → Records*
 */
export interface ArtistDocumentDataRecordsItem {
  /**
   * Record field in *Artist → Records*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: artist.records[].record
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  record: ContentRelationshipFieldWithData<
    [{ id: 'record'; fields: ['title', 'cover'] }]
  >
}

type ArtistDocumentDataSlicesSlice = never

/**
 * Content for Artist documents
 */
interface ArtistDocumentData {
  /**
   * Name field in *Artist*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: artist.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField

  /**
   * Records field in *Artist*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: artist.records[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  records: prismic.GroupField<Simplify<ArtistDocumentDataRecordsItem>>

  /**
   * Slice Zone field in *Artist*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: artist.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ArtistDocumentDataSlicesSlice> /**
   * Meta Title field in *Artist*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: artist.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField

  /**
   * Meta Description field in *Artist*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: artist.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Artist*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: artist.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>
}

/**
 * Artist document from Prismic
 *
 * - **API ID**: `artist`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArtistDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<ArtistDocumentData>, 'artist', Lang>

type RecordDocumentDataSlicesSlice = never

/**
 * Content for Record documents
 */
interface RecordDocumentData {
  /**
   * Title field in *Record*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: record.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField

  /**
   * Cover field in *Record*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: record.cover
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  cover: prismic.ImageField<never>

  /**
   * Artist field in *Record*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: record.artist
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  artist: ContentRelationshipFieldWithData<[{ id: 'artist'; fields: ['name'] }]>

  /**
   * Record ID field in *Record*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: record.record_id
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  record_id: prismic.KeyTextField

  /**
   * Year field in *Record*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: record.year
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  year: prismic.NumberField

  /**
   * Original Year field in *Record*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: record.original_year
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  original_year: prismic.NumberField

  /**
   * Label field in *Record*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: record.label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField

  /**
   * Discs field in *Record*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: record.discs
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  discs: prismic.NumberField

  /**
   * Notes field in *Record*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: record.notes
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  notes: prismic.RichTextField

  /**
   * Slice Zone field in *Record*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: record.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<RecordDocumentDataSlicesSlice> /**
   * Meta Title field in *Record*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: record.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField

  /**
   * Meta Description field in *Record*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: record.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Record*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: record.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>
}

/**
 * Record document from Prismic
 *
 * - **API ID**: `record`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RecordDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<RecordDocumentData>, 'record', Lang>

export type AllDocumentTypes = ArtistDocument | RecordDocument

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig
    ): prismic.WriteClient<AllDocumentTypes>
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>
  }

  namespace Content {
    export type {
      ArtistDocument,
      ArtistDocumentData,
      ArtistDocumentDataRecordsItem,
      ArtistDocumentDataSlicesSlice,
      RecordDocument,
      RecordDocumentData,
      RecordDocumentDataSlicesSlice,
      AllDocumentTypes,
    }
  }
}
